### ISSUE TITLE
AKA 2.0 - Ideas

### ISSUE THREAD

**Issue by gplopes** [owvy/aka#12]
- Migrate to TS
- Maybe integrate with Alfred (?)  (inspiration https://github.com/denisidoro/navi)
- Update aka config:

### 1.  `basePath`
> multiple commands can share the same path.

v1 (current)
```yml
  services:
     args:
       service1: (cd ~/project;  start service1)
       service2: (cd ~/project;  start service2)
```

v2
```yml
  services:
     basePath: ~/project
     args:
       service1: start service1
       service2: start service2
```
-------
### 2.  support listed command
> better way to list multiple commands at once

v1 (current)
```yml
  services:
     args:
       service1: start service-fe && start service-be
```

v2
```yml
  services:
     args:
       service1: 
          - start service-fe
          - start service-be
```
-------
### 3. rename args and use only run
> it can identify if there are multiple commands or now

````bash
  > aka services be
````

v1 (current)
```yml
  # single command
  services:
     run: start service-fe

  ## multiple commands
  services:
     args:
      be: start service-be
      fe: start service-fe
```

v2
```yml
  # single command
  services:
     run: start service-fe

  ## multiple commands
  services:
     run:
      be: start service-be
      fe: start service-fe
```
